### PR TITLE
correct sha256sum

### PR DESCRIPTION
**Pull request by rodinux**
Think it is the correct sum for this package.

## Problem

- *Corrupt source when upgrading*

## Solution

- *Correct sha256sum for the release*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
Ok, I am not sure, but I have got this issue trying upgrade today https://paste.yunohost.org/raw/pibivorepo
To verify I have updated the sources packages and just do a 
```
sha256sum grav-admin-v1.7.30.zip 
3417ab561ac87ab0bfcf85c352e6a7b5ce8b33d212f67f50fc79e638bf590ab4  grav-admin-v1.7.30.zip
sha256sum grav-update-v1.7.30.zip 
f724d8c84c9a6f3ec62a1744dfdfbef15273a57c1bf519aecbd5c24b169e3421  grav-update-v1.7.30.zip
```

Is the good way to proceed ?

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by rodinux** [comment]
Seems Ok, can you push this patch @tituspijean ?

**Comment by tituspijean** [comment]
Thank you!

**Comment by rodinux** [comment]
Thanks.

**Pull request merged**
