### PR TITLE
Update check_process

### PR DESCRIPTION
**Pull request by kay0u**

### CODE REVIEW

**Comment by Jibec** [comment]
hello, what is the reason for this?

**Comment by tituspijean** [comment]
This is due to [lasts CI checks](https://ci-apps.yunohost.org/ci/job/5220):

```
Upgrade from Version 1.3.1... [Test 5/11]

Preliminary install...
Start the LXC container.
Create witness files...
Working time: 6 seconds.
Working time: 4 seconds.
Installation failed. (1)
Error: yunohost cli - Invalid choice for argument 'is_public', it must be one of yes, no, y, n, 1, 0

Installation failed...
--- FAIL ---
```

The issue lies with the capital Y. Yunohost only allows `yes, no, y, n, 1, 0` all without small caps. Moreover, we are unconsistent between `install` and `upgrade`.

https://github.com/YunoHost-Apps/grav_ynh/blob/f59d2c9de6856b4f50b41d2a6d4775b5f4d203bf/scripts/upgrade#L30
https://github.com/YunoHost-Apps/grav_ynh/blob/f59d2c9de6856b4f50b41d2a6d4775b5f4d203bf/scripts/install#L108

**Comment by kay0u** [comment]
I think, it could fix the CI to stay at level 7

**Comment by Jibec** [comment]
Please merge to testing.
I'm also fixing the nginx warnings.

**Comment by Jibec** [comment]
OK, so no end user impact, let me first fix other suggestions from linter. I'll open a new PR.

**Pull request merged**
