### PR TITLE
Upgrade to v1.7.6

### PR DESCRIPTION
**Pull request by tituspijean**

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Failing due to v1.6.26 not being installable any more. What do you think, let's ignore the matter? Maybe up the version of "upgrade from older commit" test?

**Comment by ericgaspar** [comment]
Let's try to upgrade from 1.6.27

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
:|

**Comment by ericgaspar** [comment]
let's try from the current master version then...

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
