### PR TITLE
update to 1.6.0-beta6, php7.2

### PR DESCRIPTION
**Pull request by Salamandar**

### CODE REVIEW

**Comment by Jibec** [comment]
Thanks for your work!

I'm afraid I won't agree to push this.
Please open a different PR if you want to be a maintainer, so we can discuss it, and let's focus on php 7 here.

We are using a helper in core:
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/backend#L203

It need to accept a parameter to tell we are using php 7.2 before we can use it in a clean way. And add some compatibility checks in upgrade script.

So, you did most of what is needed for grav, what is missing is core ynh.
Do you feel like doing it or would you like to open an issue in https://github.com/YunoHost/issues?
-- 
Jean-Baptiste Holcroft

**Comment by tituspijean** [comment]
I am having similar issue with PHP 7.1/7.2 for the [next Flarum update](https://github.com/YunoHost-Apps/flarum_ynh/issues/107). It seems that @anmol26s has already adapted the [helper in Firefly-III](https://github.com/YunoHost-Apps/Firefly-III_ynh/blob/e1caea57cec6efc40be33a9f561ae03acaae2671/scripts/_common.sh#L18). We could start from it.

**Comment by Jibec** [comment]
in addition, as pointed by Aleks: https://mamot.fr/web/statuses/101184599378470321
php 7.2 is not available in Debian 9.

We can't fix it in this way.

I asked Aleks to discuss with the team about this.

**Comment by Jibec** [comment]
I suggest to wait Debian 10 to support grav 1.6
until then, I would like to maintain only grav 1.5

**Comment by Jibec** [comment]
you can add a "thumb up" on this ticket: https://github.com/getgrav/grav/issues/2054#issuecomment-414132709

**Comment by Jibec** [comment]
debian 10 is coming, one step at a time: https://release.debian.org/

**Comment by tituspijean** [comment]
I have created [branch `v1.6.16`](https://github.com/YunoHost-Apps/grav_ynh/tree/v1.6.16) to test installing additional PHP versions with Grav v1.6+.

**Comment by tituspijean** [comment]
Maybe we can move forward with this? It would close #13 #16 #36.
I will make sure the branch can be merged, move to PHP7.3 and so on.

**Pull request closed without merging**
