### PR TITLE
Actually disable in-app backup, do not backup backups nor cache

### LINKED ISSUE #162: Disable Grav's internal daily backups
### Describe the bug

I've seen this PR proposed but not merged in the end #96.
As of today, it seems to me that grav has automatic backup enabled by default.
I recently installed various sites, didn't set any `user/config/backup.yaml` file, and all of them have a backup folder filled with daily backups.

I'm confused because `system/config/backup.yaml` has the following content:
```yaml
purge:
    trigger: space
    max_backups_count: 25
    max_backups_space: 5
    max_backups_time: 365

profiles:
  -
    name: 'Default Site Backup'
    root: '/'
    schedule: false
    schedule_at: '0 3 * * *'
    exclude_paths: "/backup\r\n/cache\r\n/images\r\n/logs\r\n/tmp"
    exclude_files: ".DS_Store\r\n.git\r\n.svn\r\n.hg\r\n.idea\r\n.vscode\r\nnode_modules"
```

Schedule being set to `false`, I imagine no backup should be going on.
Is there something I'm misunderstanding.
At this point I'm even wondering if it might be a bug in grav itself. But I feel strange that nobody noticed it yet.
Anybody has some ideas of what may be going on?

### Context

- I have access to my server: *Through SSH, through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- YunoHost version: *11.2.10.3*
- Grav_ynh version: *1.7.44~ynh1*

### Steps to reproduce

- Install grav
- Let it sit for some days
- Check contents in `/var/www/grav/backup`

### Expected behavior

No backup should be automatically made, unless the user creates a `user/config/backups.yaml` file specifying they want backups (or do the same via grav admin).

### Additional comments

Looking at the backup grav_ynh bacup script, it seems that the whole `/var/www/grav` dir is backed up (if I'm not mistaken reading `ynh_backup --src_path="$install_dir"`). It seems to me that the `/var/www/grav/backup` directory shouldn't be backed up. Otherwise we're backing up the backups, which is a bit weird.

### PR DESCRIPTION
**Pull request by tituspijean**
Fixes #162 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
> Don't know what you think of it, since cache cleanup maybe is a good thing to have by default.

Indeed, though it may increase load on lower spec devices?

> Also, I was wondering about the permissions used. Shouldn't the group be set to www-data [as is done globally in the install script](https://github.com/YunoHost-Apps/grav_ynh/blob/68edebace10aabac9ccaa171353f522d54c0d92c/scripts/install#L26)?

Actually the PHP pool runs as $app:$app so there is no influence on that here. I'm actually wondering now about the relevance of `www-data`... ha yes, a look to nginx.conf makes sense of its use.

**Comment by tituspijean** [comment]
Also, the relevant part of the install script is actually https://github.com/YunoHost-Apps/grav_ynh/blob/68edebace10aabac9ccaa171353f522d54c0d92c/scripts/install#L63 ;)

Though I concede mixing `$app:www-data` and `$app:$app` files may not make actual sense.

**Comment by eauchat** [comment]
Yes, for coherence I'd have used the same permissions everywhere, but I've no idea what's better in fact.

**Comment by tituspijean** [comment]
Let's merge this as-is. I do not want to give myself a headache with files permissions right now. :)

**Pull request merged**
