### PR TITLE
Upgrade to 1.7.0

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem
- 1.7.0 has been released!

## Solution
- Upgrade!
- Check that PHP >=7.3.6 is installed by YNH

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
Meanwhile, v.1.7.3 is out... we should definitely wait a few days after any major release. 😅

**Comment by tituspijean** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
