### PR TITLE
Testing

### LINKED ISSUE #65: Broken installation via webadmin, broken LDAP / Login
### Describe the bug

When trying to install the App via the Web admin panel, it freezes before I can click Install, the ask selections for domain and admin user cannot be accessed, it only shows a loading indicator forever.
Also, when trying to install via CLI (which works) and then trying to login, no user is able to login. grav.user and grav.admin permissions are given to a user, but when trying to login, it just rejects with "login failed.."
There are no meaningful logs in /var/www/grav/user/logs/grav.log or nginx or php-fpm. The normal behaviour that the grav LDAP plugin logs access rejections to this log is not present, the log only contains infos about flex-objects.

The app is broken because of these issues and can not be used

### Context

- Hardware: Contabo VPS L SSD
- YunoHost version: 4.1.7.4 (stable)
- I have access to my server: SSH + Webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: latest (1.7.7)
- If upgrading, current package version: -

### Steps to reproduce

- Install via cli
    ```sh
    sudo yunohost app install grav
    ```
- Assign grav.admin and grav.user perms to user/group
- Try to login with the user
- Fails wiith "Failed to login..."
- No logs are produced of the incident

### Expected behavior

Installation via Webadmin works
Login with authorized user works

### Logs

Logs are empty! No Grav-related info/error messages produced, apart from the nginx 200 entries in the access logs, which are not very helpful

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem
Closes #65 
 - v1.7.10 available

## Solution
- `bin/gpm` has to be run from `$final_path`
- Upgrade to v1.7.10

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Review by alexAubin — APPROVED** [review]

**Comment by Stylix58** [comment]
What? no merge?

**Comment by tituspijean** [comment]
Your wishes are my commands.

**Pull request merged**
