### PR TITLE
Upgrade to 1.6.26, YNH v3.7 permissions system and PHP version handling

### LINKED ISSUE #13: Consider LDAP integration
[This LDAP plugin](https://github.com/trilbymedia/grav-plugin-login-ldap) seems promising for interfacing with YNH as it handles both user-restricted pages and admin panel

- [x] Integrate the plugin
- [x] Configure the plugin with YNH's parameters
- [x] Create admin's user file, including their proper role. (not needed for YNH <3.7)

### LINKED ISSUE #16: Grav 1.6 will require php7.1
I want to update the Grave to 1.6 but that will require php7.1 thus breaking the update.
Solution use php7.1 instead of php7.0.

### LINKED ISSUE #36: warning displayed in YunoHost's installation logs
Bonjour

here's the warning displayed in YunoHost's installation logs 

2020-03-29 21:59:17,240: WARNING - /!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem
- PHP7.0 is not supported anymore by Grav
- grav_ynh does not support logging in with YunoHost users credentials
- YunoHost v3.7 holds a new permissions systems, based on ldap groups

## Solution
- Include support for other PHP versions (here 7.3)
- Install an LDAP extension for Grav
- Use the new permissions system

## PR Status
- [x] Code finished.
- [x] Tested with Package_check
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/view/tituspijean/job/grav_ynh%20(tituspijean)/)
[Level 7](https://ci-apps-dev.yunohost.org/jenkins/view/tituspijean/job/grav_ynh%20(tituspijean)/18/console)

Resolves #13, resolves #16, resolves #36
Closes #19

### CODE REVIEW

**Comment by SiM** [comment]
Can't wait to have this PR merged ! :stuck_out_tongue_winking_eye:

**Comment by tituspijean** [comment]
As stated in the linked issues, we prefer to wait to have official support for various PHP versions, instead of the support implemented here. :)

**Comment by SiM** [comment]
Ok, thank you for your answer.
I just read the linked issues, but I'm not sure to understand: 
the official support of various php version will come in 3.8, isn't it?
So after the 3.8 release you need to rework some stuff before merging this PR?

**Comment by tituspijean** [comment]
You're absolutely correct. ;) If you still want to try it, you can checkout the branch locally and install it. But after v3.8 release I will remove the part that installs PHP 7.3 and rely on the official helpers.

**Comment by tomgue** [comment]
Quelqu'un s'occupe toujours de ce repos ??
La version 1.7 va bientôt être dispo...

**Comment by tituspijean** [comment]
> 
> 
> Quelqu'un s'occupe toujours de ce repos ??
> La version 1.7 va bientôt être dispo...

You are most welcome to contribute if you have any deadline regarding v1.7. :)

---

As of last commit, CI checks are all OK except for Upgrade and Restore steps. It seems it is an issue related to PHP-FPM, but I cannot find *what*.

**Comment by tituspijean** [comment]
As of a9dd25f, `testing` branch is Level 7 and all objectives of this PR are met. Merging in 3 days.

**Pull request merged**
